### ISSUE TITLE
Frontend not working

### ISSUE THREAD

**Issue by siddhu003** [Chaitanya-Phaniswar/car-management#1]
Why am I getting this error while accessing the frontend?
![Screenshot from 2024-11-18 15-52-05](https://github.com/user-attachments/assets/2f3638ff-6043-450c-857c-0d1196ca8b28)

**Comment by Chaitanya-Phaniswar** [comment]
Hey Siddhu, Thanks for pointing out the issue. 
There was updates after i have deployed this version of the application u can access the Final Live application at 
https://car-management-ruddy.vercel.app/.

**Comment by siddhu003** [comment]
Thanks!! This works
